name: LWJGL Build

on:
  push:
    branches:
      - master

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_PARAMS: --acl public-read --cache-control "public,must-revalidate,proxy-revalidate,max-age=0"
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  SPVC_PARAMS: -DSPIRV_CROSS_STATIC=OFF -DSPIRV_CROSS_SHARED=ON -DSPIRV_CROSS_CLI=OFF -DSPIRV_CROSS_ENABLE_TESTS=OFF -DSPIRV_CROSS_SKIP_INSTALL=ON -DSPIRV_CROSS_WERROR=ON -DSPIRV_CROSS_FORCE_PIC=ON

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        ARCH: [x64, arm32, arm64, mips64]
        include:
          # -----
          - ARCH: x64
            PACKAGES: gcc-4.8 g++-4.8
            CC: CC=gcc-4.8 CXX=g++-4.8
            CMAKE_PARAMS:
            STRIP: strip
          # -----
          - ARCH: arm32
            PACKAGES: gcc-4.8-arm-linux-gnueabihf g++-4.8-arm-linux-gnueabihf libc6-dev-armhf-cross
            CC: CC=arm-linux-gnueabihf-gcc-4.8 CXX=arm-linux-gnueabihf-g++-4.8
            CMAKE_PARAMS: -DCMAKE_TOOLCHAIN_FILE=../XCompile-lwjgl.cmake -DSYSTEM_NAME=Linux -DSYSTEM_PROCESSOR=arm
            STRIP: arm-linux-gnueabihf-strip
          # -----
          - ARCH: arm64
            PACKAGES: gcc-5-aarch64-linux-gnu g++-5-aarch64-linux-gnu libc6-dev-arm64-cross
            CC: CC=aarch64-linux-gnu-gcc-5 CXX=aarch64-linux-gnu-g++-5
            CMAKE_PARAMS: -DCMAKE_TOOLCHAIN_FILE=../XCompile-lwjgl.cmake -DSYSTEM_NAME=Linux -DSYSTEM_PROCESSOR=aarch64
            STRIP: aarch64-linux-gnu-strip
          # -----
          - ARCH: mips64
            PACKAGES: gcc-5-mips64el-linux-gnuabi64 g++-5-mips64el-linux-gnuabi64 libc6-dev-mips64el-cross
            CC: CC=mips64el-linux-gnuabi64-gcc-5 CXX=mips64el-linux-gnuabi64-g++-5
            CMAKE_PARAMS: -DCMAKE_TOOLCHAIN_FILE=../XCompile-lwjgl.cmake -DSYSTEM_NAME=Linux -DSYSTEM_PROCESSOR=mips64
            STRIP: mips64el-linux-gnuabi64-strip
    env:
      LWJGL_ARCH: ${{matrix.ARCH}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - run: sudo apt-get -yq install ${{matrix.PACKAGES}}
        name: Install dependencies
      - run: |
          mkdir build
          cd build
          ${{matrix.CC}} cmake ${{env.SPVC_PARAMS}} -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0" ${{matrix.CMAKE_PARAMS}} ..
        name: Configure build
      - run: |
          cd build
          cmake --build .
          ${{matrix.STRIP}} libspirv-cross-c-shared.so
        name: Build
      - run: aws s3 cp build/libspirv-cross-c-shared.so s3://build.lwjgl.org/nightly/linux/${{matrix.ARCH}}/libspirv-cross.so $S3_PARAMS
        name: Upload artifact
      - run: |
          git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > spirv-cross.so.git
          aws s3 cp spirv-cross.so.git s3://build.lwjgl.org/nightly/linux/${{matrix.ARCH}}/ $S3_PARAMS
        name: Upload git revision

  macos:
    name: macOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ARCH: [x64, arm64]
        include:
          - ARCH: x64
            CMAKE_PARAMS: -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9
          - ARCH: arm64
            CMAKE_PARAMS: -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_TOOLCHAIN_FILE=../XCompile-lwjgl.cmake -DSYSTEM_NAME=Darwin -DSYSTEM_PROCESSOR=aarch64
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - run: |
          mkdir build
          cd build
          cmake ${{env.SPVC_PARAMS}} -DCMAKE_BUILD_TYPE=Release ${{matrix.CMAKE_PARAMS}} ..
        name: Configure build
      - run: |
          cd build
          cmake --build .
          strip -u -r libspirv-cross-c-shared.dylib
        name: Build
      - run: aws s3 cp build/libspirv-cross-c-shared.dylib s3://build.lwjgl.org/nightly/macosx/${{matrix.ARCH}}/libspirv-cross.dylib $S3_PARAMS
        name: Upload artifact
      - run: |
          git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > libspirv-cross.dylib.git
          aws s3 cp libspirv-cross.dylib.git s3://build.lwjgl.org/nightly/macosx/${{matrix.ARCH}}/ $S3_PARAMS
        name: Upload git revision

  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ARCH: [x86, x64, arm64]
        include:
          - ARCH: x86
            PLATFORM: Win32
          - ARCH: x64
            PLATFORM: x64
          - ARCH: arm64
            PLATFORM: ARM64
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 16 2019" -A ${{matrix.PLATFORM}} ${{env.SPVC_PARAMS}} ..
        shell: cmd
        name: Configure build
      - run: |
          cd build
          cmake --build . --config Release
        shell: cmd
        name: Build
      - run: aws s3 cp build\Release\spirv-cross-c-shared.dll s3://build.lwjgl.org/nightly/windows/${{matrix.ARCH}}/spirv-cross.dll ${{env.S3_PARAMS}}
        shell: cmd
        name: Upload artifact
      - run: |
          git log --first-parent --pretty=format:%%H HEAD~2..HEAD~1 > spirv-cross.dll.git
          aws s3 cp spirv-cross.dll.git s3://build.lwjgl.org/nightly/windows/${{matrix.ARCH}}/ ${{env.S3_PARAMS}}
        shell: cmd
        name: Upload git revision
